# Cloudflare Pages configuration
pages_build_output_dir = "dist"

# Environment variables for Cloudflare Pages
[env.production.vars]
VITE_API_URL = "https://api.stargate.ci"
VITE_APP_NAME = "Stargate.ci"
VITE_CONTACT_EMAIL = "contact@stargate.ci"
