name = "stargate-ci"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = "frontend/dist"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Environment variables
[vars]
VITE_API_URL = "https://api.stargate.ci"
VITE_APP_NAME = "Stargate.ci"
VITE_CONTACT_EMAIL = "contact@stargate.ci"
